# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.chickens_model <- function(parameters_patch, betas, max_time, dt, solver_type) {
    .Call(`_chickens_chickens_model`, parameters_patch, betas, max_time, dt, solver_type)
}

